#!/bin/bash

SLOC=`readlink -f $0`
SDIR=`dirname $SLOC`

DB_USR=$1
DB_NAME='stronghold'

if [ "$DB_USR" == "" ] ; then
	DB_USR=${USER}
fi

psql -U "${DB_USR}" -f "${SDIR}/CreateDatabase.sql"
psql -U "${DB_USR}" -d "${DB_NAME}" -f "${SDIR}/CreateTables.sql"
psql -U "${DB_USR}" -d "${DB_NAME}" -f "${SDIR}/InsertInitialData.sql"

