#!/bin/bash

psql -U postgres -W template1 -f ../GameServer/Persistence/PostgreSQL/CreateDatabase.sql -w ;
psql -U postgres -W stronghold -f ../GameServer/Persistence/PostgreSQL/CreateTables.sql -w ;
psql -U postgres -W stronghold -f ../GameServer/Persistence/PostgreSQL/InsertInitialData.sql -w ;
