#!/bin/bash

SRC_DIR=$1

if [ "$SRC_DIR" == "" ] ; then
    echo "*** need directory with sources as argument" > /dev/fd/2
    exit 1
fi

echo '#!/usr/bin/env python3'
echo ''
echo "# Extracted from ${SRC_DIR}"
echo ''

find "${SRC_DIR}" -name 'ID[A-Z]*' -exec \
 sed -srn -e 's/.*(ID_\w*)\s*=?\s*(\(\s*(.*)\s*\)|.*)\s*;/\1 = \2/p' -e '1~0a#{}\' {} \; |\
 sed -r 's/(.*)\(([0-9]+)\)(.*)/\1\2\3/'

echo ''

