#!/usr/bin/env python3

# Extracted from ../TUSCore/GameServer

#../TUSCore/GameServer/Property/IDProperty.hpp
ID_PROPERTY_BUILDING_CAPACITY = 1
ID_PROPERTY_HUMAN_DISMISSABLE = 2
ID_PROPERTY_HUMAN_ENGAGEABLE = 3
ID_PROPERTY_HUMAN_PRODUCTION = 4
#../TUSCore/GameServer/Common/IDHolder.hpp
ID_HOLDER_CLASS_SETTLEMENT = 1
ID_HOLDER_CLASS_SETTLER = 2
ID_HOLDER_CLASS_TRANSPORT = 3
ID_HOLDER_CLASS_TROOP = 4
#../TUSCore/GameServer/Building/IDBuilding.hpp
ID_BUILDING_CLASS_DEFENSIVE = 1
ID_BUILDING_CLASS_GOLD = 2
ID_BUILDING_CLASS_REGULAR = 3
ID_BUILDING_CLASS_SPECIAL = 4
ID_BUILDING_DEFENSIVE_BARBICAN = (1, 1)
ID_BUILDING_DEFENSIVE_BATTLEMENTS = (1, 2)
ID_BUILDING_DEFENSIVE_CASEMATE = (1, 3)
ID_BUILDING_DEFENSIVE_CIRCUMVALLATION = (1, 4)
ID_BUILDING_DEFENSIVE_DONJON = (1, 5)
ID_BUILDING_DEFENSIVE_MACHICOLATION = (1, 6)
ID_BUILDING_DEFENSIVE_PORTCULLIS = (1, 7)
ID_BUILDING_DEFENSIVE_POSTERN = (1, 8)
ID_BUILDING_DEFENSIVE_VIEWING_TOWER = (1, 9)
ID_BUILDING_GOLD_ALTAR_OF_WISHES = (2, 1)
ID_BUILDING_GOLD_COMMUNICATION_TOWERS = (2, 2)
ID_BUILDING_GOLD_ETERNAL_CALENDAR = (2, 3)
ID_BUILDING_GOLD_HUNTER_OF_METEORS = (2, 4)
ID_BUILDING_GOLD_HUNTER_OF_RAINS = (2, 5)
ID_BUILDING_GOLD_HUNTER_OF_STORMS = (2, 6)
ID_BUILDING_GOLD_HUNTER_OF_WINDS = (2, 7)
ID_BUILDING_GOLD_NECROPOLIS = (2, 8)
ID_BUILDING_GOLD_ORACLE = (2, 9)
ID_BUILDING_GOLD_PORTAL_OF_ELEMENTS = (2, 10)
ID_BUILDING_GOLD_PSIONIC_ACADEMY = (2, 11)
ID_BUILDING_GOLD_TOWER_OF_CHAOS = (2, 12)
ID_BUILDING_REGULAR_BARRACKS = (3, 1)
ID_BUILDING_REGULAR_FARM = (3, 2)
ID_BUILDING_REGULAR_FORGE = (3, 3)
ID_BUILDING_REGULAR_GUILD = (3, 4)
ID_BUILDING_REGULAR_HOUSE = (3, 5)
ID_BUILDING_REGULAR_MARKETPLACE = (3, 6)
ID_BUILDING_REGULAR_MINE = (3, 7)
ID_BUILDING_REGULAR_QUARRY = (3, 8)
ID_BUILDING_REGULAR_SAWMILL = (3, 9)
ID_BUILDING_REGULAR_SCHOOL = (3, 10)
ID_BUILDING_REGULAR_STEELWORKS = (3, 11)
ID_BUILDING_REGULAR_TEMPLE = (3, 12)
ID_BUILDING_SPECIAL_AQUEDUCT = (4, 1)
ID_BUILDING_SPECIAL_BAWDY_HOUSE = (4, 2)
ID_BUILDING_SPECIAL_COMMERCIAL_PORT = (4, 3)
ID_BUILDING_SPECIAL_COURT = (4, 4)
ID_BUILDING_SPECIAL_GRANARY = (4, 5)
ID_BUILDING_SPECIAL_SEWERAGE = (4, 6)
#../TUSCore/GameServer/Resource/IDResource.hpp
ID_RESOURCE_COAL = 1
ID_RESOURCE_FOOD = 2
ID_RESOURCE_GOLD = 3
ID_RESOURCE_IRON = 4
ID_RESOURCE_MANA = 5
ID_RESOURCE_ROCK = 6
ID_RESOURCE_WOOD = 7
#../TUSCore/GameServer/Human/IDHuman.hpp
ID_HUMAN_CLASS_SOLDIER = 1
ID_HUMAN_CLASS_SORCERER = 2
ID_HUMAN_CLASS_SPY = 3
ID_HUMAN_CLASS_WORKER = 4
ID_HUMAN_SOLDIER_ARCHER = (1, 1)
ID_HUMAN_SOLDIER_HORSEMAN = (1, 2)
ID_HUMAN_SOLDIER_INFANTRYMAN = (1, 3)
ID_HUMAN_SORCERER_EARTH = (2, 1)
ID_HUMAN_SORCERER_FIRE = (2, 2)
ID_HUMAN_SORCERER_WATER = (2, 3)
ID_HUMAN_SORCERER_WIND = (2, 4)
ID_HUMAN_SPY_AGENT = (3, 1)
ID_HUMAN_SPY_SPY = (3, 2)
ID_HUMAN_SPY_THUG = (3, 3)
ID_HUMAN_WORKER_BLACKSMITH = (4, 1)
ID_HUMAN_WORKER_BREEDER = (4, 2)
ID_HUMAN_WORKER_DRUID = (4, 3)
ID_HUMAN_WORKER_FARMER = (4, 4)
ID_HUMAN_WORKER_FISHERMAN = (4, 5)
ID_HUMAN_WORKER_JOBLESS = (4, 6)
ID_HUMAN_WORKER_LUMBERJACK = (4, 7)
ID_HUMAN_WORKER_MERCHANT = (4, 8)
ID_HUMAN_WORKER_MINER = (4, 9)
ID_HUMAN_WORKER_OFFICIAL = (4, 10)
ID_HUMAN_WORKER_PRIEST = (4, 11)
ID_HUMAN_WORKER_STEELWORKER = (4, 12)
ID_HUMAN_WORKER_STONE_MASON = (4, 13)
ID_HUMAN_WORKER_TEACHER = (4, 14)
#../TUSCore/GameServer/Cost/IDCostType.hpp
ID_COST_TYPE_BUILDING_BUILD = 1
ID_COST_TYPE_BUILDING_DESTROY = 2
ID_COST_TYPE_HUMAN_DISMISS = 3
ID_COST_TYPE_HUMAN_ENGAGE = 4
ID_COST_TYPE_HUMAN_LIVING = 5

